version: '3.8'

services:
  ebook-search:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      # Bind mount source code for development - changes reflect immediately
      - ".:/app"
      # Mount your ebook directories from host to container
      # COMMENTED OUT - These were mounting personal Mac directories:
      # - "${HOME}/Documents:/mnt/documents:ro"
      # - "${HOME}/Downloads:/mnt/downloads:ro" 
      
      # For Raspberry Pi books or dummy directory for development
      - "${PI_BOOKS_PATH:-./dummy_books}:/mnt/books:ro"
      
      # COMMENTED OUT - Personal Mac directory:
      # - "${HOME}/Desktop:/mnt/desktop:ro"
      
      # Add specific ebook directories only - uncomment and modify as needed:
      # - "${HOME}/Books:/mnt/books:ro"
      # - "/path/to/your/ebooks:/mnt/ebooks:ro"
      # - "/path/to/calibre/library:/mnt/calibre:ro"
      # - "/home/pi/Elements/Books:/mnt/kindle:ro"  # Add Kindle books mount if path exists
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    container_name: ebook-search 
