version: '3.8'

services:
  ebook-search:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      # Bind mount source code for development - changes reflect immediately
      - ".:/app"
      # Mount your ebook directories from host to container
      - "${HOME}/Documents:/mnt/documents:ro"
      - "${HOME}/Downloads:/mnt/downloads:ro" 
      - "${PI_BOOKS_PATH:-./dummy_books}:/mnt/books:ro"  # Pi books or dummy dir for development
      - "${HOME}/Desktop:/mnt/desktop:ro"
      # Add more volume mounts as needed for your ebook locations
      # Example for additional directories:
      # - "/path/to/your/ebooks:/mnt/ebooks:ro"
      # - "/path/to/calibre/library:/mnt/calibre:ro"
      # - "/home/pi/Elements/Books:/mnt/kindle:ro"  # Add Kindle books mount if path exists
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    container_name: ebook-search 
